spring.application.name=LABORATORIO

# DATASOURCE SPRING
# protocolo-puerto-nombre
spring.datasource.url=jdbc:postgresql://localhost:5432/testlab 
spring.datasource.username=testlab
spring.datasource.password=testlab123
# Le dice a Spring qué driver JDBC usar.
spring.datasource.driver-class-name=org.postgresql.Driver


# ---->> JPA / HIBERNATE <<-----
spring.jpa.hibernate.ddl-auto=none
#Sesion de hibernate
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true